import express from "express";
import path from "path";
import fs from "fs";
import crypto from "node:crypto";
import { spawn, execFileSync, type ChildProcess } from "node:child_process";
import { DATA_DIR, dataFile } from "./server_paths";
import { addPreset, autoAssign, profileFor, publicSettings, remove, secret, setRoles, settings, upsert } from "./provider_config";
import { PROVIDER_CATALOG } from "./src/providers/catalog";
import { chat, listModels, synthesize, testProvider, transcribe } from "./src/providers/runtime";
import { localStatus, stopLocalRuntime } from "./src/local/runtime";
import type { ChatMessage, ProviderProfile, ProviderRole } from "./src/providers/types";

const PORT=3000, AGENT_URL="http://127.0.0.1:8765", AGENT_TOKEN=crypto.randomUUID();
const MEMORY_FILE=dataFile("memories.json"), SETTINGS_FILE=dataFile("settings.json"), LOG_DIR=dataFile("logs");
fs.mkdirSync(LOG_DIR,{recursive:true});
const log=(name:string,text:string)=>{try{fs.appendFileSync(path.join(LOG_DIR,`${name}.log`),`[${new Date().toISOString()}] ${text}\n`)}catch{}};
type Memory={id:string;category:string;text:string;createdAt:string;updatedAt:string};
const loadMemories=():Memory[]=>{try{return JSON.parse(fs.readFileSync(MEMORY_FILE,"utf8"))}catch{return[]}};
const saveMemories=(items:Memory[])=>fs.writeFileSync(MEMORY_FILE,JSON.stringify(items,null,2),{mode:0o600});

let agent:ChildProcess|null=null;
function commandExists(cmd:string){try{execFileSync(cmd,["--version"],{stdio:"ignore"});return true}catch{return false}}
function startAgent(){if(agent&&!agent.killed)return;const env={...process.env,VAANI_AGENT_HOST:"127.0.0.1",VAANI_AGENT_PORT:"8765",VAANI_AGENT_TOKEN:AGENT_TOKEN,VAANI_APP_EXECUTABLE:process.env.VAANI_APP_EXECUTABLE||"vaani"};let cmd="",args:string[]=[],cwd=process.cwd();const frozen=process.env.VAANI_AGENT_EXE;if(frozen&&fs.existsSync(frozen)){cmd=frozen;cwd=path.dirname(frozen)}else if(commandExists("python3")){cmd="python3";args=["-m","uvicorn","desktop_agent.main:app","--host","127.0.0.1","--port","8765"]}else if(commandExists("python")){cmd="python";args=["-m","uvicorn","desktop_agent.main:app","--host","127.0.0.1","--port","8765"]}else{log("errors","No Python or packaged agent found");return}agent=spawn(cmd,args,{cwd,env,stdio:"ignore",windowsHide:true});agent.on("exit",code=>{log("errors",`Agent exited ${code}`);agent=null});agent.on("error",e=>{log("errors",`Agent error ${e.message}`);agent=null})}
async function agentHealth(){try{const r=await fetch(`${AGENT_URL}/health`,{signal:AbortSignal.timeout(2000)});return r.ok?await r.json():null}catch{return null}}
async function ensureAgent(){let h=await agentHealth();if(h)return h;startAgent();for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,500));h=await agentHealth();if(h)return h}return null}
const ALLOWED_TOOLS=new Set(["openApplication","closeApplication","openWebsite","searchWeb","searchYouTube","searchGoogle","searchGitHub","createFile","readFile","renameFile","deleteFile","moveFile","openFolder","listFiles","searchFiles","volumeUp","volumeDown","muteToggle","setVolume","requestPowerAction","executePowerAction","minimizeWindow","maximizeWindow","closeWindow","switchApplication","copySelected","pasteClipboard","getClipboard","clearClipboard","takeScreenshot","saveScreenshot","analyzeScreenshot","readScreen","desktopBrowserOpen","desktopBrowserNavigate","desktopBrowserSearch","desktopBrowserClick","desktopBrowserType","desktopBrowserScroll","createPythonFile","runPythonScript","createProjectFolder","writeCodeFile","systemInfo","gpuInfo","temperatureInfo","brightnessUp","brightnessDown","setBrightness","enableAutoStart","disableAutoStart","getAutoStartStatus","getPlatformCapabilities"]);
async function runTool(name:string,args:Record<string,unknown>){if(!ALLOWED_TOOLS.has(name))return{ok:false,error:`Tool ${name} is not allowed.`};if(!(await ensureAgent()))return{ok:false,error:"Vaani desktop agent is offline."};try{const r=await fetch(`${AGENT_URL}/execute`,{method:"POST",headers:{"Content-Type":"application/json","X-VAANI-Token":AGENT_TOKEN},body:JSON.stringify({tool:name,args}),signal:AbortSignal.timeout(30000)});const body:any=await r.json().catch(()=>({}));return r.ok?body:{ok:false,error:body.detail||`Agent HTTP ${r.status}`}}catch(e:any){return{ok:false,error:e.message}}}

const s=(description:string)=>({type:"string",description}),n=(description:string)=>({type:"number",description}),b=(description:string)=>({type:"boolean",description});
const fn=(name:string,description:string,properties:Record<string,unknown>={},required:string[]=[])=>({type:"function",function:{name,description,parameters:{type:"object",properties,...(required.length?{required}:{})}}});
const TOOLS=[
fn("openApplication","Open an installed Linux application",{name:s("Application name")},["name"]),fn("closeApplication","Close an application",{name:s("Application name"),force:b("Force close")},["name"]),fn("openWebsite","Open a website",{name:s("Website name"),url:s("Full URL")}),fn("searchWeb","Search the web",{query:s("Search query"),engine:s("google, youtube, github, bing or duckduckgo")},["query"]),fn("openFolder","Open a folder",{name:s("Folder alias"),path:s("Folder path")}),fn("listFiles","List files",{path:s("Folder path"),name:s("Folder alias"),pattern:s("Glob pattern")}),fn("searchFiles","Search files",{name:s("Filename or glob"),extension:s("Extension"),folder:s("Folder")}),fn("createFile","Create a text file",{path:s("Path"),content:s("Text content"),overwrite:b("Replace existing")},["path"]),fn("readFile","Read a text file",{path:s("Path"),max_chars:n("Maximum characters")},["path"]),fn("renameFile","Rename a file",{path:s("Path"),new_name:s("New name")},["path","new_name"]),fn("moveFile","Move a file",{path:s("Path"),destination:s("Destination")},["path","destination"]),fn("deleteFile","Move a file to Trash",{path:s("Path")},["path"]),fn("volumeUp","Increase volume",{amount:n("Fraction or percentage")}),fn("volumeDown","Decrease volume",{amount:n("Fraction or percentage")}),fn("setVolume","Set volume percent",{percent:n("0-100")},["percent"]),fn("muteToggle","Toggle mute"),fn("brightnessUp","Increase brightness",{amount:n("Percentage")}),fn("brightnessDown","Decrease brightness",{amount:n("Percentage")}),fn("setBrightness","Set brightness",{percent:n("1-100")},["percent"]),fn("getClipboard","Read clipboard text"),fn("pasteClipboard","Copy text and paste when supported",{text:s("Text")}),fn("takeScreenshot","Capture the screen",{include_image:b("Return image")}),fn("readScreen","Read visible text with OCR"),fn("systemInfo","Read system information"),fn("getPlatformCapabilities","Detect Linux capabilities"),fn("requestPowerAction","Request confirmation for a power action",{action:s("shutdown, restart, sleep or lock")},["action"]),fn("executePowerAction","Execute an explicitly confirmed power action",{action:s("Power action"),execute_token:s("Short-lived confirmation token")},["action","execute_token"]),fn("minimizeWindow","Minimize active window on Xorg"),fn("maximizeWindow","Maximize a window on Xorg",{title:s("Optional window title")}),fn("switchApplication","Switch application on Xorg",{title:s("Optional title")})];

const history:ChatMessage[]=[];
function systemPrompt(){const memory=loadMemories().map(x=>`- ${x.text}`).join("\n");return`You are Vaani, a concise Indian-built Linux voice assistant. Prioritize useful work over visual effects. Use the supplied tools for requested computer actions. The system is Ubuntu and may use Wayland or Xorg. Never claim a restricted Wayland action succeeded. Never execute a power action without the two-step confirmation flow. Keep spoken answers natural and brief.\n\nDurable memories:\n${memory||"None yet."}`}
async function modelFor(role:ProviderRole,messages:ChatMessage[],tools?:unknown[]){const profile=profileFor(role);return{profile,result:await chat(profile,secret(profile.id),messages,tools)}}
async function answer(text:string){history.push({role:"user",content:text});if(history.length>30)history.splice(0,history.length-30);const messages:ChatMessage[]=[{role:"system",content:systemPrompt()},...history];let profile:ProviderProfile,result:any;try{({profile,result}=await modelFor("assistant",messages,TOOLS))}catch(primary:any){log("errors",`Primary provider: ${primary.message}`);({profile,result}=await modelFor("fallback",messages,TOOLS))}const actions:any[]=[];for(let round=0;round<5;round++){messages.push(result.assistantMessage);if(!result.toolCalls.length){const output=result.text||"Done.";history.push({role:"assistant",content:output});return{text:output,provider:profile.name,actions}}for(const call of result.toolCalls){const toolResult=await runTool(call.name,call.arguments);actions.push({tool:call.name,ok:toolResult.ok!==false});messages.push({role:"tool",tool_call_id:call.id,name:call.name,content:JSON.stringify(toolResult)})}result=await chat(profile,secret(profile.id),messages,TOOLS)}throw new Error("Too many consecutive tool calls.")}
async function extractMemory(userText:string,assistantText:string){try{const p=profileFor("memory"),prompt=`Return only JSON {"memories":[{"category":"identity|preference|goal|project|relationship|emotional|behavior","text":"durable third-person fact"}]}. Ignore commands, greetings, secrets and temporary information. User: ${userText}\nAssistant: ${assistantText}`;const r=await chat(p,secret(p.id),[{role:"system",content:"Extract durable memories as strict JSON only."},{role:"user",content:prompt}]);const raw=r.text.replace(/^```json\s*|\s*```$/g,"");const parsed=JSON.parse(raw),items=loadMemories();for(const candidate of parsed.memories||[]){if(!candidate.text||items.some(x=>x.text.toLowerCase()===String(candidate.text).toLowerCase()))continue;const now=new Date().toISOString();items.push({id:crypto.randomUUID(),category:candidate.category||"behavior",text:String(candidate.text).slice(0,500),createdAt:now,updatedAt:now})}saveMemories(items.slice(-300))}catch(e:any){log("errors",`Memory extraction skipped: ${e.message}`)}}

async function main(){const app=express();
app.post("/api/transcribe",express.raw({type:["audio/wav","application/octet-stream"],limit:"30mb"}),async(req,res)=>{try{const p=profileFor("speechToText"),text=await transcribe(p,secret(p.id),req.body as Buffer);res.json({text,provider:p.name})}catch(e:any){res.status(502).json({error:e.message})}});
app.use(express.json({limit:"3mb"}));
app.get("/api/provider-catalog",(_q,res)=>res.json({providers:PROVIDER_CATALOG}));
app.get("/api/local-status",async(_q,res)=>res.json(await localStatus()));
app.get("/api/providers",(_q,res)=>res.json(publicSettings()));
app.post("/api/providers/from-preset",(req,res)=>{try{res.json(addPreset(String(req.body.presetId||"")))}catch(e:any){res.status(400).json({error:e.message})}});
app.post("/api/providers",(req,res)=>{try{const saved=upsert(req.body.profile,req.body.apiKey);res.json({...saved,hasSecret:!!req.body.apiKey||!!secret(saved.id)})}catch(e:any){res.status(400).json({error:e.message})}});
app.delete("/api/providers/:id",(req,res)=>{try{remove(req.params.id);res.json({ok:true})}catch(e:any){res.status(400).json({error:e.message})}});
app.post("/api/providers/roles",(req,res)=>{try{res.json({roles:setRoles(req.body.roles||{})})}catch(e:any){res.status(400).json({error:e.message})}});
app.post("/api/providers/:id/auto-assign",(req,res)=>{try{res.json({roles:autoAssign(req.params.id)})}catch(e:any){res.status(400).json({error:e.message})}});
app.get("/api/providers/:id/models",async(req,res)=>{const p=settings().profiles.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:"Provider not found."});try{res.json({models:await listModels(p,secret(p.id))})}catch(e:any){res.status(502).json({error:e.message})}});
app.post("/api/providers/:id/test",async(req,res)=>{const p=settings().profiles.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:"Provider not found."});const result=await testProvider(p,secret(p.id));res.status(result.ok?200:502).json(result)});
app.post("/api/chat",async(req,res)=>{try{const text=String(req.body?.text||"").trim();if(!text)return res.status(400).json({error:"Text is required."});const result=await answer(text);res.json(result);void extractMemory(text,result.text)}catch(e:any){log("errors",e.message);res.status(502).json({error:e.message})}});
app.post("/api/speak",async(req,res)=>{try{const text=String(req.body?.text||"").trim();if(!text)return res.status(400).json({error:"Text is required."});const p=profileFor("textToSpeech"),audio=await synthesize(p,secret(p.id),text);res.type("audio/wav").send(audio)}catch(e:any){res.status(502).json({error:e.message})}});
app.get("/api/agent-health",async(_q,res)=>{const h=await ensureAgent();res.json(h?{online:true,tool_count:h.tool_count,capabilities:h.capabilities||{}}:{online:false})});
app.get("/api/memories",(_q,res)=>res.json(loadMemories()));app.delete("/api/memories/:id",(req,res)=>{saveMemories(loadMemories().filter(x=>x.id!==req.params.id));res.json({ok:true})});
app.get("/api/settings",(_q,res)=>{try{res.json(JSON.parse(fs.readFileSync(SETTINGS_FILE,"utf8")))}catch{res.json({})}});app.post("/api/settings",async(req,res)=>{const next={...(()=>{try{return JSON.parse(fs.readFileSync(SETTINGS_FILE,"utf8"))}catch{return{}}})(),...req.body};fs.writeFileSync(SETTINGS_FILE,JSON.stringify(next,null,2),{mode:0o600});if("autoStart" in req.body)void runTool(req.body.autoStart?"enableAutoStart":"disableAutoStart",{});res.json(next)});
app.use(express.static(path.join(process.cwd(),"dist")));app.get("*",(_q,res)=>res.sendFile(path.join(process.cwd(),"dist","index.html")));const server=app.listen(PORT,"127.0.0.1",()=>{log("startup",`Vaani started on ${PORT}`);void ensureAgent()});const stop=()=>{agent?.kill("SIGTERM");stopLocalRuntime();server.close()};process.on("SIGTERM",stop);process.on("SIGINT",stop)}
main().catch(e=>{console.error(e);process.exit(1)});
