import type { ProviderPreset, ProviderProfile } from "./types";

export const PROVIDER_CATALOG: ProviderPreset[] = [
  {id:"vaani-local",name:"Vaani Local",kind:"vaani-local",group:"local",description:"Included offline text, microphone and voice engine. No account or API key.",baseUrl:"http://127.0.0.1:11435/v1",requiresKey:false,keyLabel:"No key required",apiStyle:"openai",capabilities:{chat:true,tools:true,speechToText:true,textToSpeech:true},chatModels:["vaani-local"],speechModels:["vaani-whisper"],ttsModels:["vaani-piper"]},
  {id:"ollama",name:"Ollama",kind:"ollama",group:"local",description:"Use models already installed with Ollama on this computer.",baseUrl:"http://127.0.0.1:11434/v1",requiresKey:false,keyLabel:"Optional key",apiStyle:"openai",capabilities:{chat:true,tools:true},chatModels:["qwen2.5:3b","qwen2.5:7b","llama3.2:3b","mistral:7b"],speechModels:[],ttsModels:[]},
  {id:"lmstudio",name:"LM Studio",kind:"lmstudio",group:"local",description:"Connect to the local OpenAI-compatible server in LM Studio.",baseUrl:"http://127.0.0.1:1234/v1",requiresKey:false,keyLabel:"Optional key",apiStyle:"openai",capabilities:{chat:true,tools:true},chatModels:[],speechModels:[],ttsModels:[]},
  {id:"openai",name:"OpenAI",kind:"openai",group:"cloud",description:"OpenAI chat, Whisper transcription and speech models.",baseUrl:"https://api.openai.com/v1",requiresKey:true,keyLabel:"OpenAI API key",apiStyle:"openai",capabilities:{chat:true,tools:true,speechToText:true,textToSpeech:true},chatModels:["gpt-4o-mini","gpt-4o"],speechModels:["whisper-1"],ttsModels:["tts-1"]},
  {id:"anthropic",name:"Anthropic Claude",kind:"anthropic",group:"cloud",description:"Claude models with native Anthropic tool calling.",baseUrl:"https://api.anthropic.com/v1",requiresKey:true,keyLabel:"Anthropic API key",apiStyle:"anthropic",capabilities:{chat:true,tools:true},chatModels:["claude-sonnet-4-5","claude-haiku-4-5"],speechModels:[],ttsModels:[]},
  {id:"google",name:"Google Gemini",kind:"google",group:"cloud",description:"Gemini through Google's OpenAI-compatible API.",baseUrl:"https://generativelanguage.googleapis.com/v1beta/openai",requiresKey:true,keyLabel:"Gemini API key",apiStyle:"openai",capabilities:{chat:true,tools:true},chatModels:["gemini-2.5-flash","gemini-2.5-pro"],speechModels:[],ttsModels:[]},
  {id:"groq",name:"Groq",kind:"groq",group:"cloud",description:"Fast hosted open models and Whisper transcription.",baseUrl:"https://api.groq.com/openai/v1",requiresKey:true,keyLabel:"Groq API key",apiStyle:"openai",capabilities:{chat:true,tools:true,speechToText:true},chatModels:["llama-3.3-70b-versatile","openai/gpt-oss-20b"],speechModels:["whisper-large-v3-turbo","whisper-large-v3"],ttsModels:[]},
  {id:"openrouter",name:"OpenRouter",kind:"openrouter",group:"cloud",description:"One key for many hosted model providers.",baseUrl:"https://openrouter.ai/api/v1",requiresKey:true,keyLabel:"OpenRouter API key",apiStyle:"openai",capabilities:{chat:true,tools:true},chatModels:["openai/gpt-4o-mini","anthropic/claude-sonnet-4","google/gemini-2.5-flash"],speechModels:[],ttsModels:[]},
  {id:"huggingface",name:"Hugging Face",kind:"huggingface",group:"cloud",description:"Hosted open models and multilingual speech recognition.",baseUrl:"https://router.huggingface.co/v1",requiresKey:true,keyLabel:"Hugging Face token",apiStyle:"openai",capabilities:{chat:true,tools:true,speechToText:true},chatModels:["deepseek-ai/DeepSeek-R1-0528","Qwen/Qwen2.5-72B-Instruct"],speechModels:["openai/whisper-large-v3"],ttsModels:[]},
  {id:"mistral",name:"Mistral AI",kind:"mistral",group:"cloud",description:"Mistral's hosted chat and tool-capable models.",baseUrl:"https://api.mistral.ai/v1",requiresKey:true,keyLabel:"Mistral API key",apiStyle:"openai",capabilities:{chat:true,tools:true},chatModels:["mistral-small-latest","mistral-large-latest"],speechModels:[],ttsModels:[]},
  {id:"deepseek",name:"DeepSeek",kind:"deepseek",group:"cloud",description:"DeepSeek chat and reasoning models.",baseUrl:"https://api.deepseek.com/v1",requiresKey:true,keyLabel:"DeepSeek API key",apiStyle:"openai",capabilities:{chat:true,tools:true},chatModels:["deepseek-chat","deepseek-reasoner"],speechModels:[],ttsModels:[]},
  {id:"xai",name:"xAI Grok",kind:"xai",group:"cloud",description:"Grok models through the xAI API.",baseUrl:"https://api.x.ai/v1",requiresKey:true,keyLabel:"xAI API key",apiStyle:"openai",capabilities:{chat:true,tools:true},chatModels:["grok-3-mini","grok-3"],speechModels:[],ttsModels:[]},
  {id:"together",name:"Together AI",kind:"together",group:"cloud",description:"Hosted open-weight models through an OpenAI-compatible API.",baseUrl:"https://api.together.xyz/v1",requiresKey:true,keyLabel:"Together API key",apiStyle:"openai",capabilities:{chat:true,tools:true},chatModels:["meta-llama/Llama-3.3-70B-Instruct-Turbo","Qwen/Qwen2.5-72B-Instruct-Turbo"],speechModels:[],ttsModels:[]},
  {id:"perplexity",name:"Perplexity",kind:"perplexity",group:"cloud",description:"Search-grounded Sonar models.",baseUrl:"https://api.perplexity.ai",requiresKey:true,keyLabel:"Perplexity API key",apiStyle:"openai",capabilities:{chat:true},chatModels:["sonar","sonar-pro"],speechModels:[],ttsModels:[]},
  {id:"custom",name:"Custom provider",kind:"custom",group:"custom",description:"Any OpenAI-compatible local or hosted API.",baseUrl:"http://127.0.0.1:8000/v1",requiresKey:false,keyLabel:"API key (optional)",apiStyle:"openai",capabilities:{chat:true},chatModels:[],speechModels:[],ttsModels:[]},
];

export function presetFor(idOrKind?: string) {
  return PROVIDER_CATALOG.find(p=>p.id===idOrKind || p.kind===idOrKind);
}
export function profileFromPreset(presetId:string, id?:string):ProviderProfile {
  const p=presetFor(presetId);
  if(!p) throw new Error("Unknown provider preset.");
  return {id:id||`${p.id}-${Date.now()}`,presetId:p.id,name:p.name,kind:p.kind,apiStyle:p.apiStyle,baseUrl:p.baseUrl,chatModel:p.chatModels[0]||"",speechModel:p.speechModels[0]||"",ttsModel:p.ttsModels[0]||"",enabled:true,requiresKey:p.requiresKey,capabilities:{...p.capabilities}};
}
